project:
  type: book
  output-dir: docs

book:
  title: "Final Project"
  author: "Jessie Lai"
  date: "7/28/2025"
  chapters:
    - index.qmd
    - question.qmd
    - import.qmd
    - tidy.qmd
    - transform.qmd
    - visualize.qmd
    - model.qmd
    - communicate.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true
    clean-url: false
editor: visual